# Generated by Django 4.2.2 on 2023-07-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='languate',
            new_name='language',
        ),
    ]
