# Generated by Django 4.2.2 on 2023-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_languate_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avartar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
