# Generated by Django 4.2.2 on 2023-07-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perks',
            new_name='Perk',
        ),
    ]
