# Generated by Django 4.2.2 on 2023-07-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('experiences', '0003_perk_category_alter_perk_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perk',
            name='category',
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
